export default {
    ASC_SYMBOL: "ASC_SYMBOL",
    DESC_SYMBOL: "DESC_SYMBOL",
    ASC_VOLUME: "ASC_VOLUME",
    DESC_VOLUME: "DESC_VOLUME",
    ASC_CHANGE: "ASC_CHANGE",
    DESC_CHANGE: "DESC_CHANGE"
}