export default {
    CREATE_WALLET: "CREATE_WALLET",
    UNLOCK_METAMASK: "UNLOCK_METAMASK",
    UNLOCK_PRIVATE_KEY: "UNLOCK_PRIVATE_KEY",
    DEPOSIT_ETH: "DEPOSIT_ETH",
    DEPOSIT_TOKEN: "DEPOSIT_TOKEN",
    TRADE: "TRADE"
}