
export default {
    WEB_SOCKET_CONSTRUCTED: "WEB_SOCKET_CONSTRUCTED",
    WEB_SOCKET_OPENED: "WEB_SOCKET_OPENED",
    WEB_SOCKET_CLOSED: "WEB_SOCKET_CLOSED",
    WEB_SOCKET_ERROR: "WEB_SOCKET_ERROR",
    WEB_SOCKET_CONNECT_ERROR: "WEB_SOCKET_CONNECT_ERROR",
    SELECT_TOKEN: "SELECT_TOKEN",
    ORDERS_RECEIVED: "ORDERS_RECEIVED",
    MESSAGE_RECEIVED_MARKET: "MESSAGE_RECEIVED_MARKET",
    MESSAGE_RECEIVED_ORDERS: "MESSAGE_RECEIVED_ORDERS",
    MESSAGE_RECEIVED_TRADES: "MESSAGE_RECEIVED_TRADES",
    MESSAGE_RECEIVED_FUNDS: "MESSAGE_RECEIVED_FUNDS",
    CHANGE_BIDS_PAGE: "CHANGE_BIDS_PAGE",
    CHANGE_OFFERS_PAGE: "CHANGE_OFFERS_PAGE",
    CHANGE_TRADES_PAGE: "CHANGE_TRADES_PAGE",
    ACCOUNT_RETRIEVED: "ACCOUNT_RETRIEVED",
    BALANCE_RETRIEVED: "BALANCE_RETRIEVED",
    ETH_TRANSACTION: "ETH_TRANSACTION",
    TOK_TRANSACTION: "TOK_TRANSACTION"
}
