
export default {
    LOAD_CONFIG: "LOAD_CONFIG",
    CONFIG_LOADED: "CONFIG_LOADED",
    WEB_SOCKET_CONSTRUCTED: "WEB_SOCKET_CONSTRUCTED",
    WEB_SOCKET_OPENED: "WEB_SOCKET_OPENED",
    WEB_SOCKET_CLOSED: "WEB_SOCKET_CLOSED",
    WEB_SOCKET_ERROR: "WEB_SOCKET_ERROR",
    TOKEN_SELECTED: "TOKEN_SELECTED",
    ORDERS_RECEIVED: "ORDERS_RECEIVED",
    MESSAGE_RECEIVED_MARKET: "MESSAGE_RECEIVED_MARKET",
    MESSAGE_RECEIVED_ORDERS: "MESSAGE_RECEIVED_ORDERS",
    //REQUEST_TOKEN: "REQUEST_TOKEN",
}
